### ISSUE TITLE
Tagging av oppgaver

### ISSUE THREAD

**Issue by Skagevang** [kodeklubben/oppgaver#410]
Tagging av oppgaver skjer på følgende måte:
- Selve oppgaven skal bli tagget. Ikke kurset
- Taggingen skal være på engelsk uten mellomrom. F.eks `tags: topic: [games, robot]`
- Det blir laget en fil med kun godkjente grupper og tags
- Det blir laget filer for oversettelser til gruppene og taggene
- Alt ligger i oppgaverepoet

Dvs at hvis man legger til et nytt kurs eller oppgave og vil tagge denne med en tag som ikke ligger i filen over forhåndsdefinerte tags, må man legge til det der. Og legge til en oversettelse for det i filene for oversetting. Disse filene kommer asap. Med en gang jeg har fått lagt opp filen med forhåndsdefinerte tagger, er det bare å kjøre på med å tagge oppgavene. Dette bør være ganske lett på de største kursene, da disse oppgavene har fått lærereveiledning med "tags" under ## Oppgaven passer til: {.check}

**Comment by arve0** [comment]
> Det blir laget en fil med kun godkjente grupper og tags

Kan vi endre denne? Forslag: 

- En fil med **eksisterende** grupper og tags blir generert automatisk og lagt til i repo som oppslag for oppgaveskrivere.

**Comment by Skagevang** [comment]
Det er jo en mulighet i tillegg til at filen skal brukes til å sjekke om oppgaven har gyldige tags. Og legges inn i tester senere?

**Comment by arve0** [comment]
Nettopp. Det gir også en fin workflow når en legger til nye tags:

- Hvis det er meningen må filen genereres på ny, hvis ikke feiles testen.
- Hvis det er en stavefeil, oppdages dette i testen.

**Comment by NorwegianKiwi** [comment]
Dette med å automatisk generere filen med tags, blir ikke det litt vanskelig når alle tags skal oversettes til diverse språk?

**Comment by arve0** [comment]
Tenker det avhenger av om tags *må* relateres en til en / en til mange for alle oversettelser.

Hvis man er redd for at tags ikke oversettes kan man lage en enkel test for det:

- For hver oppgave som er oversatt
  - Forsørg at begge oppgavene inneholder like mange tags.

**Comment by NorwegianKiwi** [comment]
Forslag til hvordan vi kan legge inn tags i oppgaverepoet:
Vi lager en folder som heter `tags`, og flytter `filterTags.md` inn dit. Så omdøper vi `filterTags.md` til `keys.md`.

Deretter lager vi én fil per språk: `translation_nb.md`, `translation_en.md` osv.
Disse filene kan ha følgende format:
```
groups:
  language: Språk
  topic: Tema
  ...
tags:
  language:
    nb: Norsk bokmål
    nn: Norsk nynorsk
    ...
  topic:
    app: App
    electronics: Elektronikk
    ...
  ...
tooltips:
  topic:
    app: Dette er tooltip-teksten til app
    electronics: Dette er tooltip-teksten til Elektronikk
    …
```

Og tooltips-treet trenger ikke være komplett, kun de som skal ha tooltip trenger være der.

**Comment by NorwegianKiwi** [comment]
Hvis jeg skjønte @tjesi rett, så likte han bedre følgende forslag:
```
groups:
  language: Språk
  topic: Tema
  ...
tags:
  language:
    nb: Norsk bokmål
    nn: Norsk nynorsk
    ...
  topic:
    app:
      name: App
      tooltip: Dette er tooltip-teksten til app
    electronics:
      name: Elektronikk
      tooltip: Dette er tooltip-teksten til Elektronikk
    game: Spill
    ...
  ...
```

Her er det valgfritt om man vil ha med `name` og `tooltip` (som for app og electronics), eller bare en string (som for game og de to språkene nn og nb); dersom man bare har en string, så blir dette automatisk name, og tooltip forsvinner.

Man kunne også si at man alltid måtte ha med `name`. Noe kommentarer?

**Comment by NorwegianKiwi** [comment]
Jeg har tenkt litt til, og siden det er tanken at `keys.md` (som i dag heter filterTags.md) kommer til å se slik ut (jeg har fjernet "tags:" øverst):
```
---
topic: #Logical AND
  - app #Tasks for making apps to mobiles and tablets such as appinventor and swift
  - electronics #Includes external devices such as Microbit Arduino Raspberry pi lego mindstorms.
  - step_based #Interactive web-based courses that guides you through small concepts/tasks one step at the time. Such as code.org sessions by Khan Academy and Codecademy.
  - block_based #Programming-language based on Blockly
  - text_based #Programming-language based on text
  - minecraft #Minecraft-related tasks
  - web #Web-related tasks
  - game #Interactive programs with game elements
  - robot #Physical objects that moves
  - animation #Machine-made cartoons
subject: #Logical OR
  - mathematics
  - science
  - programming
  - technology
  - music
  - norwegian
  - english
  - arts_and_crafts
  - social_science
grade: #Logical OR
  - preschool #Projects aimed at preschool students
  - primary #Projects aimed at students in grade 1.-4.
  - secondary #Projects aimed at students in grade 5.-7.
  - junior #Projects aimed at students in grade 8.-10.
  - senior #Projects aimed at students in high school.
---
```
så er det kanskje mer naturlig at translation_nb.md ser slik ut?
```
topic:
  NAME: Tema
  LOGICAL_OR: false
  TAGS:
    app:
      NAME: App
      TOOLTIP: App tooltip
    electronics:
      NAME: Elektronikk
    ...
subject:
  NAME: Fag
  LOGICAL_OR: true
  TAGS:
    mathematics:
      NAME: Matematikk
    norwegian:
      NAME: Norsk
    ...
...
```
